LATIN_TO_GREEK = {

    # multi-letter lowercase
    'th': 'θ',
    'ph': 'φ',
    'ch': 'χ',
    'ps': 'ψ',
    'ks': 'ξ',

    # multi-letter uppercase
    'TH': 'Θ',
    'PH': 'Φ',
    'CH': 'Χ',
    'PS': 'Ψ',
    'KS': 'Ξ',

    # multi-letter title case
    'Th': 'Θ',
    'Ph': 'Φ',
    'Ch': 'Χ',
    'Ps': 'Ψ',
    'Ks': 'Ξ',

    # single letters lowercase
    'a': 'α',
    'b': 'β',
    'g': 'γ',
    'd': 'δ',
    'e': 'ε',
    'z': 'ζ',
    'h': 'η',
    'i': 'ι',
    'k': 'κ',
    'l': 'λ',
    'm': 'μ',
    'n': 'ν',
    'o': 'ο',
    'p': 'π',
    'r': 'ρ',
    's': 'σ',
    't': 'τ',
    'u': 'υ',
    'f': 'φ',
    'x': 'χ',

    # single letters uppercase
    'A': 'Α',
    'B': 'Β',
    'G': 'Γ',
    'D': 'Δ',
    'E': 'Ε',
    'Z': 'Ζ',
    'H': 'Η',
    'I': 'Ι',
    'K': 'Κ',
    'L': 'Λ',
    'M': 'Μ',
    'N': 'Ν',
    'O': 'Ο',
    'P': 'Π',
    'R': 'Ρ',
    'S': 'Σ',
    'T': 'Τ',
    'U': 'Υ',
    'F': 'Φ',
    'X': 'Χ',
}   