# Common Mandarin phrases - ONLY standalone phrases that are unambiguous
MANDARIN_PHRASES = {
    # Greetings
    'ni3 hao3': '你好',
    'ni3 hao3 ma': '你好吗',
    'zao3 shang4 hao3': '早上好',
    'zao3 an1': '早安',
    'wan3 an1': '晚安',
    'wan3 shang4 hao3': '晚上好',
    'zhong1 wu3 hao3': '中午好',
    'zai4 jian4': '再见',
    'bai2 bai2': '拜拜',
    'hui2 jian4': '回见',
    'ming2 tian1 jian4': '明天见',
    
    # Thanks & apologies
    'xie4 xie4': '谢谢',
    'xie4 xie5 ni3': '谢谢你',
    'duo1 xie4': '多谢',
    'gan3 xie4': '感谢',
    'bu4 yong4 xie4': '不用谢',
    'bu2 ke4 qi4': '不客气',
    'bu4 ke4 qi5': '不客气',
    'dui4 bu4 qi3': '对不起',
    'bao4 qian4': '抱歉',
    'mei2 guan1 xi5': '没关系',
    'mei2 shi4': '没事',
    'bu2 hao3 yi4 si5': '不好意思',
    
    # Love & feelings
    'wo3 ai4 ni3': '我爱你',
    'ai4 ni3': '爱你',
    'xiang3 ni3': '想你',
    'xiang3 nian4': '想念',
    'xi3 huan1': '喜欢',
    'xi3 huan5 ni3': '喜欢你',
    'wo3 xi3 huan5 ni3': '我喜欢你',
    
    # Birthday & celebrations
    'sheng1 ri4 kuai4 le4': '生日快乐',
    'sheng1 ri4 kuai4 le5': '生日快乐',
    'zhu4 ni3 sheng1 ri4 kuai4 le4': '祝你生日快乐',
    'gong1 xi3': '恭喜',
    'zhu4 fu2': '祝福',
    'zhu4 he4': '祝贺',
    'xin1 nian2 kuai4 le4': '新年快乐',
    'chun1 jie2 kuai4 le4': '春节快乐',
    'guo4 nian2 hao3': '过年好',
    
    # Common questions
    'zen3 me5 le5': '怎么了',
    'zen3 me5 ban4': '怎么办',
    'shen2 me5': '什么',
    'wei2 shen2 me5': '为什么',
    'shui2': '谁',
    'na3 li3': '哪里',
    'shen2 me5 shi2 hou4': '什么时候',
    'duo1 shao3': '多少',
    'duo1 da4': '多大',
    'ji3 dian3': '几点',
    
    # Yes/No
    'shi4': '是',
    'shi4 de5': '是的',
    'dui4': '对',
    'hao3': '好',
    'hao3 de5': '好的',
    'bu4': '不',
    'bu2 shi4': '不是',
    'bu4 shi4': '不是',
    'bu4 dui4': '不对',
    'bu4 hao3': '不好',
    'mei2 you3': '没有',
    
    # Common actions
    'chi1 fan4': '吃饭',
    'he1 shui3': '喝水',
    'shui4 jiao4': '睡觉',
    'qi3 chuang2': '起床',
    'shang4 ban1': '上班',
    'xia4 ban1': '下班',
    'shang4 xue2': '上学',
    'fang4 xue2': '放学',
    'hui2 jia1': '回家',
    'zou3 ba5': '走吧',
    'qu4 ba5': '去吧',
    'lai2 ba5': '来吧',
    
    # Family
    'ba4 ba5': '爸爸',
    'ma1 ma5': '妈妈',
    'ge1 ge5': '哥哥',
    'jie3 jie5': '姐姐',
    'di4 di5': '弟弟',
    'mei4 mei5': '妹妹',
    'lao3 gong1': '老公',
    'lao3 po2': '老婆',
    'er2 zi5': '儿子',
    'nv3 er2': '女儿',
    
    # Pronouns
    'wo3': '我',
    'ni3': '你',
    'ta1': '他',
    'ta1': '她',
    'wo3 men5': '我们',
    'ni3 men5': '你们',
    'ta1 men5': '他们',
    'ta1 men5': '她们',
    
    # Common phrases
    'jia1 you2': '加油',
    'zhen1 de5': '真的',
    'zhen1 de5 ma5': '真的吗',
    'mei2 wen4 ti2': '没问题',
    'bu4 zhi1 dao4': '不知道',
    'wo3 bu4 zhi1 dao4': '我不知道',
    'bu4 yao4': '不要',
    'yao4': '要',
    'xing2': '行',
    'bu4 xing2': '不行',
}