LATIN_TO_CYRILLIC = {
    # multi-letter lowercase
    'shch': 'щ',
    'zh': 'ж',
    'kh': 'х',
    'ts': 'ц',
    'ch': 'ч',
    'sh': 'ш',
    'yo': 'ё',
    'yu': 'ю',
    'ya': 'я',
    'ye': 'е',
    'je': 'е',

    # multi-letter uppercase
    'SHCH': 'Щ',
    'ZH': 'Ж',
    'KH': 'Х',
    'TS': 'Ц',
    'CH': 'Ч',
    'SH': 'Ш',
    'YO': 'Ё',
    'YU': 'Ю',
    'YA': 'Я',
    'YE': 'Е',
    'JE': 'Е',

    # multi-letter title case
    'Shch': 'Щ',
    'Zh': 'Ж',
    'Kh': 'Х',
    'Ts': 'Ц',
    'Ch': 'Ч',
    'Sh': 'Ш',
    'Yo': 'Ё',
    'Yu': 'Ю',
    'Ya': 'Я',
    'Ye': 'Е',
    'Je': 'Е',

    # single letters lowercase
    'a': 'а',
    'b': 'б',
    'v': 'в',
    'g': 'г',
    'd': 'д',
    'e': 'е',
    'z': 'з',
    'i': 'и',
    'j': 'й',
    'k': 'к',
    'l': 'л',
    'm': 'м',
    'n': 'н',
    'o': 'о',
    'p': 'п',
    'r': 'р',
    's': 'с',
    't': 'т',
    'u': 'у',
    'f': 'ф',
    'h': 'х',  # allow plain 'h' as 'х' as well (common in some simple latin inputs)
    'y': 'ы',

    # single letters uppercase
    'A': 'А',
    'B': 'Б',
    'V': 'В',
    'G': 'Г',
    'D': 'Д',
    'E': 'Е',
    'Z': 'З',
    'I': 'И',
    'J': 'Й',
    'K': 'К',
    'L': 'Л',
    'M': 'М',
    'N': 'Н',
    'O': 'О',
    'P': 'П',
    'R': 'Р',
    'S': 'С',
    'T': 'Т',
    'U': 'У',
    'F': 'Ф',
    'H': 'Х',
    'Y': 'Ы',

    # signs
    "'": 'ь',   # soft sign
    '"': 'ъ',   # hard sign
}
